fix TestInvalidRemoteDriver() to check underlying error
commit b1a3fe49341bec714c1017067bd17d9052e5a2d6 changed how the error was
returned (which is now wrapped), causing the test to fail:

    === RUN   TestInvalidRemoteDriver
        libnetwork_test.go:1289: Did not fail with expected error. Actual error: Plugin does not implement the requested driver: plugin="invalid-network-driver", requested implementation="NetworkDriver"
    --- FAIL: TestInvalidRemoteDriver (0.01s)

Changing the test to use errors.Is()

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>
Upstream-commit: eadf839530aa18ac2cdcc689fee0a484664c5495
Component: engine