cli/command: Error return value of `cli.Apply` is not checked (errcheck)
```
cli/command/cli_test.go:297:11: Error return value of `cli.Apply` is not checked (errcheck)
	cli.Apply(
	         ^
```

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>
(cherry picked from commit 008f6a2da3e175dc13f0845ba51bb0317a36806b)
Signed-off-by: Sebastiaan van Stijn <github@gone.nl>
Upstream-commit: 10fda078a094e4d5df4309d31cb5684f5e083893
Component: cli